name: rs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - comm=0.1.2=py312h06a4308_0
  - curl=8.1.2=h409715c_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=12.1.0=h1db8e46_17
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=12.1.0=hea43390_17
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - ipython=8.20.0=py312h06a4308_0
  - jedi=0.18.1=py312h06a4308_1
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.5.0=py312h06a4308_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=21_linux64_openblas
  - libcblas=3.9.0=21_linux64_openblas
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=21_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsanitizer=12.1.0=ha89aaad_17
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=12.1.0=h1ec3361_17
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - make=4.3=hd18ef5c_1
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - openssl=3.2.1=hd590300_0
  - packaging=23.1=py312h06a4308_0
  - pango=1.50.14=hd33c08f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=23.3.1=py312h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=3.10.0=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - r-base=4.2.2=ha7d60f8_3
  - readline=8.2=h5eee18b_0
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - tornado=6.3.3=py312h5eee18b_0
  - traitlets=5.7.1=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py312h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - cffi==1.16.0
      - ipykernel==6.29.2
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - numpy==1.26.4
      - pandas==2.2.1
      - pycparser==2.21
      - pytz==2024.1
      - rpy2==3.5.15
      - scipy==1.12.0
      - tzdata==2024.1
      - tzlocal==5.2
