name: rs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - r-base=4.2
  - numpy
  - pandas
  - scipy
  - pip
  - ipykernel
  - jinja2
  - markupsafe
  - pycparser
  - pytz
  - tzdata
  - tzlocal
  - rpy2
  - pip:
      - cffi 