name: rs
channels:
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.4
  - asttokens=3.0.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - cctools_osx-arm64=1010.6
  - cffi=1.17.1
  - clang=20.1.5
  - clang-20=20.1.5
  - clang_impl_osx-arm64=20.1.5
  - clang_osx-arm64=20.1.5
  - clangxx=20.1.5
  - clangxx_impl_osx-arm64=20.1.5
  - clangxx_osx-arm64=20.1.5
  - comm=0.2.2
  - compiler-rt=20.1.5
  - compiler-rt_osx-arm64=20.1.5
  - curl=8.13.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gfortran_impl_osx-arm64=13.3.0
  - gfortran_osx-arm64=13.3.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.8
  - harfbuzz=11.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.5
  - libcurl=8.13.0
  - libcxx=20.1.5
  - libcxx-devel=20.1.5
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=13.3.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.24.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - llvm-tools=20.1.5
  - llvm-tools-20=20.1.5
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.7.1
  - numpy=2.2.6
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyzmq=26.4.0
  - r-base=4.2.3
  - r-cli=3.6.3
  - r-colorspace=2.1_0
  - r-crayon=1.5.3
  - r-ellipsis=0.3.2
  - r-envstats=2.8.1
  - r-eva=0.2.6
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fnn=1.1.4
  - r-ggplot2=3.5.1
  - r-glue=1.7.0
  - r-gtable=0.3.5
  - r-isoband=0.2.7
  - r-kernlab=0.9_32
  - r-kernsmooth=2.23_24
  - r-ks=1.14.2
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-mclust=6.1
  - r-mgcv=1.9_1
  - r-misc3d=0.9_1
  - r-multicool=1.0.1
  - r-munsell=0.5.1
  - r-mvtnorm=1.2_5
  - r-nlme=3.1_165
  - r-nloptr=2.0.3
  - r-nortest=1.0_4
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plot3d=1.4.1
  - r-pracma=2.4.4
  - r-r6=2.5.1
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rlang=1.1.4
  - r-scales=1.3.0
  - r-tibble=3.2.1
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.0
  - readline=8.2
  - rpy2=3.5.11
  - scipy=1.15.2
  - setuptools=80.8.0
  - sigtool=0.1.3
  - simplegeneric=0.8.1
  - six=1.17.0
  - stack_data=0.6.3
  - tapi=1300.6.5
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025b
  - tzlocal=5.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - mosek==11.0.20
      - pillow==11.2.1
      - pyparsing==3.2.3
      - seaborn==0.13.2
      - tabulate==0.9.0
      - tqdm==4.67.1
